# Generated by Django 5.1.7 on 2025-03-21 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource5G',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='资源名称')),
                ('resource_type', models.CharField(choices=[('network', '网络资源'), ('spectrum', '频谱资源'), ('device', '设备资源')], max_length=20, verbose_name='资源类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='资源描述')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='资源位置')),
                ('quantity', models.IntegerField(default=1, verbose_name='资源数量')),
                ('status', models.BooleanField(default=True, verbose_name='是否可用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '5G资源',
                'verbose_name_plural': '5G资源',
                'ordering': ['-created_at'],
            },
        ),
    ]
