# Generated by Django 5.1.7 on 2025-03-23 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resource5g'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('arrival_date', models.DateField(verbose_name='到货日期')),
                ('device_model', models.CharField(max_length=100, verbose_name='设备型号')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='条码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_arrivals', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '设备到货清单',
                'verbose_name_plural': '设备到货清单',
                'ordering': ['-arrival_date'],
            },
        ),
        migrations.CreateModel(
            name='DeviceDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(verbose_name='领用日期')),
                ('barcode', models.CharField(max_length=100, verbose_name='条码')),
                ('device_model', models.CharField(max_length=100, verbose_name='设备型号')),
                ('recipient_unit', models.CharField(max_length=100, verbose_name='领用单位')),
                ('recipient', models.CharField(max_length=50, verbose_name='领用人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deliveries', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '设备出货清单',
                'verbose_name_plural': '设备出货清单',
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSecurityStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_element_name', models.CharField(max_length=100, verbose_name='网管网元名称')),
                ('is_online', models.BooleanField(default=True, verbose_name='是否在线')),
                ('asset_serial_number', models.CharField(max_length=100, verbose_name='资产序列号')),
                ('last_check_time', models.DateTimeField(auto_now=True, verbose_name='最后检查时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_security_statuses', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '设备安全状态',
                'verbose_name_plural': '设备安全状态',
                'ordering': ['-last_check_time'],
            },
        ),
    ]
