# Generated by Django 5.0 on 2025-03-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_devicearrival_devicedelivery_devicesecuritystatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicesecuritystatus',
            options={'ordering': ['-last_check_time'], 'verbose_name': '设备安装状态', 'verbose_name_plural': '设备安装状态'},
        ),
        migrations.AddField(
            model_name='devicesecuritystatus',
            name='check_date',
            field=models.DateField(blank=True, null=True, verbose_name='检查日期'),
        ),
        migrations.AlterField(
            model_name='devicesecuritystatus',
            name='network_element_name',
            field=models.CharField(max_length=100, verbose_name='网元名称'),
        ),
        migrations.DeleteModel(
            name='Resource5G',
        ),
    ]
