# Generated by Django 5.0 on 2025-03-24 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_devicesecuritystatus_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除'), ('VIEW', '查看'), ('IMPORT', '导入'), ('EXPORT', '导出'), ('LOGIN', '登录'), ('LOGOUT', '登出'), ('OTHER', '其他')], max_length=20, verbose_name='操作类型')),
                ('content_type', models.CharField(choices=[('DEVICE_ARRIVAL', '设备到货'), ('DEVICE_DELIVERY', '设备出货'), ('DEVICE_SECURITY', '安装状态'), ('USER', '用户'), ('SYSTEM', '系统')], max_length=20, verbose_name='内容类型')),
                ('object_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='对象ID')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='用户代理')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户操作日志',
                'verbose_name_plural': '用户操作日志',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='core_userac_user_id_7f1b6d_idx'), models.Index(fields=['action_type'], name='core_userac_action__f27195_idx'), models.Index(fields=['content_type'], name='core_userac_content_361e83_idx'), models.Index(fields=['timestamp'], name='core_userac_timesta_384b3d_idx')],
            },
        ),
    ]
